feature/neighbor_set_inf(single feature)
Typing-Monkeys/complex-network-link-prediction pull request #39
Opened 2023-03-31 14:07 UTC by TommasoRomani

2023-03-31 15:02 UTC, ncvescera requested changes

2023-03-31 15:02 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +    M = G.number_of_edges()
Lo richiami sempre e forse sprechi tempo.
Mettilo nel main e rendilo un parametro.

2023-03-31 15:02 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +    return s_xy
Fai ritornare una matrice sparsa

2023-03-31 15:02 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +        I_Oxy = overlap_info(G, i, j, prior, likelihood)
```suggestion
        I_Oxy = overlap_info(G, i, j)
```

2023-03-31 15:02 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +def overlap_info(G:nx.Graph, x, y, prior, likelihood):
```suggestion
def overlap_info(G:nx.Graph, x, y):
```

2023-04-02 16:38 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +    res = np.zeros((G.number_of_nodes(), G.number_of_nodes()))
La matrice risultante sarà piena o può anche essere sparsa ??

Nel caso sarebbe da utilizzare direttamente una matrice sparsa.

2023-04-02 16:38 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +def overlap_info(G:nx.Graph, x, y, edge_num):
nice 👍🏻

2023-04-02 16:39 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +def overlap_info(G:nx.Graph, x, y, prior, likelihood):
Risolto in 08a9108

2023-04-02 16:39 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +        I_Oxy = overlap_info(G, i, j, prior, likelihood)
Risolto in 08a9108

2023-04-02 16:40 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +    M = G.number_of_edges()
Risolto in 08a9108

2023-04-03 09:48 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +
le operazioni `i-1` sono date dal fatto che i nomi dei nodi iniziano da 1?

2023-04-04 16:30 UTC, TommasoRomani commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +
L'ho corretto con il metodo di networkx : nx.convert_node_labels_to_integers(), riga 91

2023-04-07 09:28 UTC, ncvescera commented on src/social_network_link_prediction/other_methods/neighbor_set_information.py
> +    res = np.zeros((G.number_of_nodes(), G.number_of_nodes()))
Risolto in 1b04464

2023-04-07 09:52 UTC, ncvescera approved these changes
👍🏻

2023-04-09 10:09 UTC, CristianCosci approved these changes

2023-04-11 13:23 UTC, merged