implementato rooted page rank method
Typing-Monkeys/complex-network-link-prediction pull request #44
Opened 2023-04-01 15:56 UTC by CristianCosci

2023-04-01 15:57 UTC, CristianCosci commented
L'implementazione è corretta e funzionante ma ci sono delle cose che vorrei chiarire. I commenti fatti beni li aggiungo una volta risolto il resto

2023-04-01 16:15 UTC, ncvescera requested changes

2023-04-01 16:15 UTC, ncvescera commented on src/social_network_link_prediction/similarity_methods/global_similarity/rooted_page_rank.py
> +    A = to_adjacency_matrix(G)
Abbiamo una funzione che lo fa.
Puoi non aggiungerla ora e lo sistemiamo nel develop dopo.

2023-04-01 16:15 UTC, ncvescera commented on src/social_network_link_prediction/similarity_methods/global_similarity/rooted_page_rank.py
> +        D[node, node] = G.degree[node]
Qui penso si rompa se i nodi del grafo non hanno label che partono da 0

2023-04-01 19:27 UTC, CristianCosci commented on src/social_network_link_prediction/similarity_methods/global_similarity/rooted_page_rank.py
> +    A = to_adjacency_matrix(G)
la funzione utilizzata è quella no?

2023-04-01 19:27 UTC, CristianCosci commented on src/social_network_link_prediction/similarity_methods/global_similarity/rooted_page_rank.py
> +        D[node, node] = G.degree[node]
si esatto

2023-04-03 10:46 UTC, ncvescera approved these changes
👍🏻

2023-04-03 10:46 UTC, merged